server:
  port: 91

spring:
  application:
    name: goop-member

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.109.134:3306/gh_ums
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.208.38:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

